[package]
name = "rstack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcap = "0.9"
structopt = "0.3"
pnet = "0.28"
pnet_macros = "0.28"
pnet_macros_support = "0.28"